### ISSUE TITLE
[要望] composer.jsonとの統合例

### ISSUE THREAD

**Issue by koriym** [pj8/dbdb#5]
PHP/composerとの連携を行えたら良いと思います！

 * `composer install`で特定バージョンのMySQLがインストールできる
 * `composer test`で（停止していたら）ユニットテスト専用のMySQLのスタート、シードが復元され、テスト終了で破棄され、MySQLがストップする。
 
 今のコマンドでもかなりできると思うのですが、これらの使用例を提示するのはどうでしょうか？

**Comment by koriym** [comment]
composer pluginを作成し、このjQueryのように依存が指定できるようなものはどうでしょうか？
https://speakerdeck.com/hirak/phpcon2016?slide=25

**Comment by yuki777** [comment]
提案ありがとうございます！
これは対応したいです。

composer pluginとして作成し、
`composer require --dev yuki777/dbdb` のようにインストールし、
`composer dbdb mysql 5.7.31 3306` のようにDBサーバを起動できる。
イメージとしてはこんな感じでしょうか？

**Comment by koriym** [comment]
```
composer dbdb mysql 5.7.31 3306
```

これだと面倒なので、この情報がcomposer.jsonに記述してあるイメージです。
--> https://github.com/yuki777/dbdb/issues/5#issuecomment-781074364

**Comment by koriym** [comment]
情報は全てcomposer.jsonに書かれたあるので、composer install、 composer test だけで MySQLがインストールされ、スタートされ、終了するのが理想です。

**Comment by koriym** [comment]
@yuki777 ping

**Comment by yuki777** [comment]
# Update 2023-04-30
- [`yuki777/dbdb-php`](https://packagist.org/packages/yuki777/dbdb-php)を作りました
  - とりあえず、MySQLのみをサポートしています
- かんたんな[CI連携の設定がこちら](https://github.com/yuki777/dbdb-php-laravel/blob/main/.github/workflows/test.yaml#L20-L23)にあります
  - [結果がこちら](https://github.com/yuki777/dbdb-php-laravel/actions/runs/4843191643/jobs/8630623855#step:6:1)です。なぜか`null`になっているので要修正ですが。

**Comment by yuki777** [comment]
phpとcomposerについては
https://github.com/yuki777/dbdb-php
で議論します。
