### ISSUE TITLE
redisが起動しない

### ISSUE THREAD

**Issue by DaichiYamazaki** [pj8/dbdb#62]
以下コマンドを実行した際、エラーが発生しました。
バージョンはv2.0.2です。
```
../git/dbdb/redis/create-start.sh redis-xxx 6.0.10 16379
Downloading... https://dbdb.shueisha-artsdigital.co.jp/redis/redis-6.0.10-macos.tar.gz
Extracting...
Installing...
There are no port files for the given 'redis-xxx'.
```

**Comment by yuki777** [comment]
@DaichiYamazaki 
Issueに気がつかずですみません。

原因はこちらで
https://github.com/redis/redis/issues/12585#issuecomment-1727686241
リストに無い最新のMacOSをつかうとだめ、もしくは古いredis6.*?を使うとだめなようですね。。

とりあえずでしたら、
https://github.com/redis/redis/issues/12585#issuecomment-1729243412
のようにsrc/config.hを修正してmakeしてしまえばOKです。

**Comment by yuki777** [comment]
dbdbのredis 6.0.*のサポートを切って、
6.2.14移行をサポートするほうが良いかもしれません。

**Comment by yuki777** [comment]
6.2.14でもmakeエラーが起きているため #63 で対応します
